
language: python

services:
  - redis-server

python:
  - "3.5"
  - "3.7"

install:
  - pip install -r tests/requirements.txt
  - pip install -r requirements.txt

script:
#   - pytest tests/isolated/test_direct.py
#   - pytest tests/isolated/test_factory.py
  - pytest

after_success:
  - codecov
